[package]
name = "cristian_algorithm"
version = "0.1.0"
edition = "2021"

# Dependencias pueden ir aquí, si las hay

[[bin]]
name = "server"
path = "src/main.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
rand = "0.8.4"
